# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: ingress-nginx-dev-2
loadBalancerSourceRanges: "0.0.0.0/0,205.166.76.0/24,107.162.0.0/16"
proxyrealipcidr: 0.0.0.0/0
sslcert: arn:aws:acm:us-west-2:409389662862:certificate/b0c5e8b5-c878-4c14-bd1c-98ed63aa1dev
loadbalancertype: nlb
loadbalancerinternal: true
ingressclass: nginx-dev
