# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: ingress-nginx-uat
loadBalancerSourceRanges: "205.166.76.0/24,107.162.0.0/16"
proxyrealipcidr: 0.0.0.0/0
sslcert: arn:aws:acm:us-west-2:967060084917:certificate/b1fb7435-0584-4e38-8590-cd00bd2b1234
loadbalancertype: nlb
loadbalancerinternal: false
ingressclass: nginx-uat
