# Source:namespace/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-type: {{ .Values.loadbalancertype | quote }}
    #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.sslcert | quote }}
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    #service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-2016-08
    service.beta.kubernetes.io/aws-load-balancer-internal: {{ .Values.loadbalancerinternal | quote }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/load-balancer-source-ranges: {{ .Values.loadBalancerSourceRanges }}
  labels:
    helm.sh/chart: {{ .Values.namespace }}-2.0.3
    app.kubernetes.io/name: {{ .Values.namespace }}
    app.kubernetes.io/instance: {{ .Values.namespace }}
    app.kubernetes.io/version: 0.32.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: {{ .Values.namespace }}-controller
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ .Values.namespace }}
    app.kubernetes.io/instance: {{ .Values.namespace }}
    app.kubernetes.io/component: controller
---
