# Default values for cloudwatch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: uat-env-namespace
clustername: kgban-prod-cluster
region: us-west-2
